# Generated by Django 6.1.1 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PROFESSIONAL', 'Professional')], default='CLIENT', max_length=20),
        ),
    ]
