# Generated by Django 6.1.1 on 2026-09-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_portfolioitem_sessions_count'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_memberships', to='artists.professionalprofile')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studios.studio')),
            ],
        ),
        migrations.AddField(
            model_name='studio',
            name='members',
            field=models.ManyToManyField(related_name='studios', through='studios.StudioMembership', to='artists.professionalprofile'),
        ),
        migrations.AddConstraint(
            model_name='studiomembership',
            constraint=models.UniqueConstraint(fields=('studio', 'professional'), name='unique_studio_professional_membership'),
        ),
    ]
