# Generated by Django 6.1.1 on 2026-09-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_portfolioitem_sessions_count'),
        ('studios', '0002_studiomembership_studio_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='studios', to='artists.category'),
        ),
    ]
