# Generated by Django 6.1.1 on 2026-09-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0019_migrate_professional_studios'),
        ('studios', '0003_studio_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='studios.studiomembership')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='artists.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'service'), name='unique_membership_service')],
            },
        ),
    ]
