# Generated by Django 6.1.1 on 2026-10-02 14:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_employeeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='employeeservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
