# Generated by Django 6.1.1 on 2026-10-07 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_alter_employeeservice_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='studios.studio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('studio', 'email'), name='unique_pending_invitation_per_studio_email')],
            },
        ),
    ]
