# Generated by Django 6.1.1 on 2026-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_tattoostyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.tattoostyle'),
        ),
    ]
