# Generated by Django 6.1.1 on 2026-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofile_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoostyle',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
