# Generated by Django 6.1.1 on 2026-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_tattoostyle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoostyle',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
