# Generated by Django 6.1.1 on 2026-09-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_tattoostyle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artists/portfolio/')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='artists.artistprofile')),
                ('styles', models.ManyToManyField(blank=True, related_name='portfolio_items', to='artists.tattoostyle')),
            ],
        ),
    ]
