# Generated by Django 6.1.1 on 2026-09-21 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_portfolioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistProfile',
            new_name='ProfessionalProfile',
        ),
    ]
