# Generated by Django 6.1.1 on 2026-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_rename_artist_profile_portfolioitem_professional_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='professionals/portfolio/'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profile_images/'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='artists.tattoostyle'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='artists.category'),
        ),
    ]
