# Generated by Django 6.1.1 on 2026-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_category_alter_portfolioitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='sessions_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
