# Generated by Django 6.1.1 on 2026-09-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='artists.service'),
        ),
    ]
