# Generated by Django 6.1.1 on 2026-09-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_alter_service_duration_minutes_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='sessions_count',
        ),
    ]
