# Generated by Django 6.1.1 on 2026-09-27 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_remove_portfolioitem_sessions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='sessions_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
