# Generated by Django 6.1.1 on 2026-09-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_portfolioitem_sessions_count'),
        ('studios', '0003_studio_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='studios.studio'),
        ),
    ]
