# Generated by Django 6.1.1 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0016_service_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='studio_services', to='artists.professionalprofile'),
        ),
    ]
