# Generated by Django 6.1.1 on 2026-09-29 07:59

from django.db import migrations


def migrate_service_professionals(apps, schema_editor):
    Service = apps.get_model("artists", "Service")

    for service in Service.objects.all():
        if service.professional_id:
            service.professionals.add(service.professional_id)


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0017_service_professionals'),
    ]

    operations = [
         migrations.RunPython(
            migrate_service_professionals,
            migrations.RunPython.noop,
         ),    
    ]
