# Generated by Django 6.1.1 on 2026-10-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0020_migrate_employee_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='professionals',
        ),
    ]
