# Generated by Django 6.1.1 on 2026-10-02 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0021_remove_service_professionals'),
        ('studios', '0005_alter_employeeservice_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='professional',
        ),
        migrations.AlterField(
            model_name='service',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='studios.studio'),
        ),
    ]
